### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by utkuozdemir** [utkuozdemir/pv-migrate#12]
Not all clusters allow running as root. If possible, we should run the sshd/rsync pods with the least privilege. If not possible, evaluate other protocols.

Another option is trying to create PSP/role/rolebinding/serviceaccount to get root authorization.

**Comment by jtackaberry** [comment]
@utkuozdemir  I'm running into this limitation myself.  I can prearrange the PSP and role binding, but is it possible somehow to define the service account used by the migrate jobs?

**Comment by utkuozdemir** [comment]
I didn't work on this because:
- It's problematic/unsupported to run sshd as non-root
- PSPs are deprecated so I don't want to invest in them

But I like the idea of using a custom service account. We can add a flag like `--use-service-account my-sa`. The user would be responsible of making sure that that service account exists and authorized via RBAC as needed.

Let me know if you would create a PR for this. Otherwise I can do it in a week or so.

**Comment by jtackaberry** [comment]
Yep, I can do a PR.

**Comment by jtackaberry** [comment]
@utkuozdemir Considering it a bit further, a better UX would be for the user to specify an existing cluster role and have pv-migrate create an ephemeral SA and role binding based on that cluster role.  A bit harder to implement, but reduces the upfront effort, especially when using pv-migrate across many namespaces (as I would like to).

Would you be amenable to this approach instead?  I think a single cluster role that applies to both sshd and rsync pods would be ok, given the nature of this tool.  So perhaps a `--cluster-role` flag?

**Comment by utkuozdemir** [comment]
Hm, I think specifying a service account feels more "natural" to me. Reasons being 

- `ClusterRole` is an RBAC concept with apiVersion `rbac.authorization.k8s.io/v1`. There are other authorization modes on Kubernetes (see https://kubernetes.io/docs/reference/access-authn-authz/authorization/). ServiceAccount on the other hand is a core Kubernetes resource (`v1`).
- There are some public helm charts out there that do not support PSPs. Those charts allow the user to specify a service account name to be used. That way, it is possible to manually manage the RBAC resources and the `ServiceAccount` becomes a kind of integration point.
- Lastly, it is possible to assign a PSP using a `Role` instead of a `ClusterRole` - in this case `--cluster-role` does not cover the needs.

It feels like the most flexible and future-proof approach to me. Does it make sense?

**Comment by jtackaberry** [comment]
> It feels like the most flexible and future-proof approach to me. Does it make sense?

It certainly makes sense, and you're right that the less opinionated pv-migrate is about this the more flexible it is.  It just means I need to create a pv-migrate service account in every namespace. :)

Ok, I'll implement `--sshd-service-account` and `--rsync-service-account` per your original reply.

**Comment by utkuozdemir** [comment]
Sounds good, thank you :)

**Comment by utkuozdemir** [comment]
On the contrary, thanks for reopening. I'll try to have a look soon.

**Comment by utkuozdemir** [comment]
Aah ok this flag was from long ago. You are right, many flags are now removed in favor of the equivalent helm values, which provide much more flexibility.
