### ISSUE TITLE
pv-migrate aborts after ~2m

### ISSUE THREAD

**Issue by upstream-dmahlberg** [utkuozdemir/pv-migrate#136]
**Describe the bug**
I am trying to migrate several GB of data and see pv-migrate abort every time after ~2 minutes. This is fairly consistent across different PVCs and using different strategies. Re-running the command seems to complete the rsync though.

**To Reproduce**
`pv-migrate --log-level debug migrate --source-context <CTX> --source-namespace <Namespace> --source-path "/" --dest-context <CTX> --dest-namespace <Namespace> --dest-path "/" --strategies "svc" --ignore-mounted --dest-delete-extraneous-files <Source_PVC> <Destination_PVC>`

**Expected behavior**
The Job runs longer, potentially up to several hours.

**Console output**
```
🚀  Starting migration
❕  Extraneous files will be deleted from the destination
💭  Will attempt 1 strategies: svc
🚁  Attempting strategy: svc
🔑  Generating SSH key pair
creating 7 resource(s)
beginning wait for 7 resources with timeout of 1m0s
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
Deployment is not ready: ame/pv-migrate-i36aw-sshd. 0 out of 1 expected pods are ready
📂  Copying data...  84% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | (72.779 MB/s) [1m53s:25s]🧹  Cleaning up
uninstall: Deleting pv-migrate-i36aw
📂  Copying data...  84% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | (70.286 MB/s) [2m0s:25s]Starting delete for "pv-migrate-i36aw-sshd" Service
Starting delete for "pv-migrate-i36aw-rsync" Job
Starting delete for "pv-migrate-i36aw-sshd" Deployment
Starting delete for "pv-migrate-i36aw-sshd" Secret
Starting delete for "pv-migrate-i36aw-rsync" Secret
Starting delete for "pv-migrate-i36aw-sshd" ServiceAccount
Starting delete for "pv-migrate-i36aw-rsync" ServiceAccount
beginning wait for 7 resources to be deleted with timeout of 1m0s
purge requested for pv-migrate-i36aw
✨  Cleanup done
🔶  Migration failed with this strategy, will try with the remaining strategies
❌  Error: all strategies have failed
```

**Version**
 - Source and destination Kubernetes versions `v1.21.4`
 - Source and destination container runtimes 'containerd'
 - `pv-migrate_0.7.2_linux_x86_64.tar.gz`
 - Installation method: binary download
 - Source and destination PVC type, size and accessModes [e.g. `ReadWriteOnce, 50G, kubernetes.io/gce-pd -> pd.csi.storage.gke.io` ]

**Additional context**
Source and Destination are in the same cluster and in the same namespace. All accessing pods were stopped at the time of migration.

**Comment by utkuozdemir** [comment]
Thanks for reporting. Is it possible for you to reproduce it with `--log-format json` in addition to the `--log-level debug`? It would give me more insight on the actual error happening under the hood.

**Comment by utkuozdemir** [comment]
I found the issue and solved it on commit https://github.com/utkuozdemir/pv-migrate/commit/a3e60064fd99b4fd9bd2a92914363ccae18c7516

You were on point with the 2 minutes observation.

The issue was introduced on v0.7.2 in the following feature: https://github.com/utkuozdemir/pv-migrate/pull/127

Please give a try version v0.7.5 which I just released. If the issue persists, feel free to open a new issue.

Thanks.

**Comment by upstream-dmahlberg** [comment]
I can confirm that this issue is resolved - good job! And thanks for the fast response!
