### ISSUE TITLE
How to use your tool without internet?

### ISSUE THREAD

**Issue by rerime** [utkuozdemir/pv-migrate#146]
**Is your feature request related to a problem? Please describe.**
We have cluster without internet access
**Describe the solution you'd like**
Allow to use tool without downloading image from internet

**Describe alternatives you've considered**
Add image path variable to change default path.

**Comment by utkuozdemir** [comment]
The Kubernetes manifests rendered by the tool are backed by a Helm chart and thanks to that, they are fully customizable.

Please see the last example on the usage page - I just updated the example to be clearer: https://github.com/utkuozdemir/pv-migrate/blob/master/USAGE.md#examples

**Comment by utkuozdemir** [comment]
I'm closing this, feel free to comment/request reopen/create new issue if the method does not work.

**Comment by rerime** [comment]
Thanks, I will try replace image via helm set.
