### ISSUE TITLE
all strategies fail if the pvc's name is longer than 63 characters

### ISSUE THREAD

**Issue by goranhaji** [utkuozdemir/pv-migrate#149]
**Describe the bug**
all strategies fail if the pvc's name is longer than 63 characters
spec.template.spec.volumes[0].name: Invalid value: \"dev-cms-coremedia-delivery-unit1-persistent-commerce-cache-cae-live-unit1-0\": must be no more than 63 characters

**To Reproduce**
1. Run command ' pv-migrate migrate dev-cms-coremedia-delivery-unit1-persistent-commerce-cache-cae-live-unit1-0 commerce-cache-cae-live-unit1 --ignore-mounted  --log-format json  --log-level debug'
2. See error: 
3. {"dest":"dev-cms-coremedia-delivery-unit1-persistent-commerce-cache-cae-live-unit1-new-0","dest_ns":"","error":"Deployment.apps \"pv-migrate-h070t-src-sshd\" is invalid: [spec.template.spec.volumes[0].name: Invalid value: \"dev-cms-coremedia-delivery-unit1-persistent-commerce-cache-cae-live-unit1-0\": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[0].name: Not found: \"dev-cms-coremedia-delivery-unit1-persistent-commerce-cache-cae-live-unit1-0\"]","id":"h070t","level":"warning","msg":":large_orange_diamond: Migration failed with this strategy, will try with the remaining strategies","source":"dev-cms-coremedia-delivery-unit1-persistent-commerce-cache-cae-live-unit1-0","source_ns":"","strategy":"lbsvc","time":"2022-02-03T14:56:48+01:00"}
Error: all strategies have failed

**Expected behavior**
migrate data even if names arelonger than 63 characters

**Console output**
Add the error logs and/or the output to help us diagnose the problem.

**Version**
 - Source and destination Kubernetes versions [e.g. `v1.17.14-gke.1600`, `v1.21.1+k3s1`]
     v1.20.7
 - Source and destination container runtimes [e.g. `containerd://1.4.4-k3s2`, `docker://19.3.6`]
 - `pv-migrate` version and architecture [e.g. `v0.5.5 - darwin_x86_64`] 
       pv-migrate version 0.10.1 (commit: fdc11ada7bcde348668d03e5806ab485ac20085e) (build date: 2022-01-02T14:04:16Z)
 - Installation method [e.g. `homebrew`, binary download]
 - Source and destination PVC type, size and accessModes [e.g. `ReadWriteMany, 8G, kubernetes.io/gce-pd -> ReadWriteOnce, N/A, rancher.io/local-path` ]

**Additional context**

**Comment by utkuozdemir** [comment]
Thanks for reporting, I'll have a look into it soon.

**Comment by utkuozdemir** [comment]
I fixed it in release `v0.10.2`. Please try and let me know if it doesn't work.

**Comment by goranhaji** [comment]
it works, thanks for the quick action
