### ISSUE TITLE
New strategy: svcmesh

### ISSUE THREAD

**Issue by josepowera** [utkuozdemir/pv-migrate#175]
**Is your feature request related to a problem? Please describe.**
We have 2 clusters already connected using submariner.io. But "svc" strategy requires that both clusters are same Host ((https://github.com/utkuozdemir/pv-migrate/blob/3ddfab44559fed367394ff43070505df3789a19f/internal/strategy/svc.go#L15))

**Describe the solution you'd like**
When we run pv-migrate on Multi-cluster "mesh", where pods can already cross-communicate between clusters, strategy "svc" does not cover our scenario - as we understand "svc" strategy would run only when source and dest are in the same cluster.

Our requirement is similar to "svc" but must not check "host1=host2"

Both source and destination clusters are connected via "submariner.io". We fix service name with "--helm-set fullnameOverride=fixedname12345"

We than run "subctl export service --namespace default servicename" to expose DNS service name to be available in other cluster too.

In this case : both clusters can communicate with each other using clusterips. Cross cluster Pod Ips can be called using "curl" and services using special notation. Example: from nodes in cluster 1 we can connect to cluster 2 using "cluster2name.servicename.namespace.clusterset.local" like dns records.

**Describe alternatives you've considered**
--helm-set fullnameOverride=pvmig12345
--dest-host-override lju1.pvmig234.default.service.cluster.local 
--helm-set sshd.service.type=ClusterIp

**Additional context**
k3s 1.23

**Comment by utkuozdemir** [comment]
I think your use case is a pretty rare one, I think in most setups (even with service mesh) ClusterIPs are not expected to be accessible across clusters.

Because of that I don't think I should add a new strategy or an exception to handle this case. I'm not sure tbh how to address this in a generic way. Maybe you give a shot to`lbsvc` or `local` strategies?

**Comment by utkuozdemir** [comment]
I'll close this ticket because I don't see a generic way of doing it. Any solution would be aimed very specifically to your use case.

I suggest editing the code as you need and building your own version for your use case.

If you have any better idea, please feel free to suggest.
