### ISSUE TITLE
SSHD source resources gets uninstalled whilst the loadbalancer service is still being created

### ISSUE THREAD

**Issue by srujan07** [utkuozdemir/pv-migrate#177]
Hi ,

We are trying to migrate PVs using lbsvc strategy and when we run the command, the SSHD source resources are getting uninstalled while the lb service is still being created. I guess there is a time out of 1 min set for the resources to be ready to proceed with installing the destination rsync resources. For some reason, our lb service takes more than 1 min to get the ingress IP and it suddenly starts uninstalling the resources. I would like to know if this is expected behaviour or is there a way to increase the timeout. 

**To Reproduce**
1. Run command '.pv-migrate migrate \
  --source-kubeconfig ~/.kube/config \
  --source-context gke1 \
  --source-namespace upgradetest \
  --source-kubeconfig ~/.kube/config \
  --dest-context gke2 \
  --dest-namespace upgradetest \
  --dest-delete-extraneous-files \
  --helm-set sshd.service.loadBalancerIP=10.99.0.171 \
  --helm-set sshd.service.annotations."networking\.gke\.io/load-balancer-type"=Internal \'
3. See error
    creating 4 resource(s)
**beginning wait for 4 resources with timeout of 1m0s**
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
Service does not have load balancer ingress IP address: upgradetest/pv-migrate-abaac-src-sshd
🧹  Cleaning up
uninstall: Deleting pv-migrate-abaac-src

**Expected behavior**
successful migration

**Version**
 - Source and destination Kubernetes versions 1.22.8-gke.200
 - `pv-migrate` version 0.12.1 (commit: 8460071f3c1a7635276f8bdadf89d6b048be8d86) (build date: 2022-04-11T21:42:07Z)
 - Installation method `homebrew`
 

**Additional context**
Please let me know if you need additional info.

Thanks,
Srujan.

**Comment by utkuozdemir** [comment]
1 minute timeout is hardcoded. Need to make it configurable with a flag. Thanks for reporting, I'll look into it.

**Comment by utkuozdemir** [comment]
Just released `v0.13.0` with the new `--helm-timeout` flag, which should address your issue. Let me know if you still have issues :)

**Comment by srujan07** [comment]
> Just released `v0.13.0` with the new `--helm-timeout` flag, which should address your issue. Let me know if you still have issues :)

Woww, that's a very quick fix. Thank you, we will try it out the new flag and let you know.
