### ISSUE TITLE
pv-migrate is not working if the pvc is used by a running pod

### ISSUE THREAD

**Issue by sshingarapu** [utkuozdemir/pv-migrate#180]
**Describe the bug**
pvc is not getting copied if the pvc is being used by a running pod in kubernetes. Tried with --ignore-mounted option to ignore but the tool is throwing Multi-Attach volume error in sshd pod

pv-migrate version: v0.13.0

**To Reproduce**
Below is the pvc template which we used
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

Pvc is created by the above template and it is using by running pod. Now if i try to copy this pvc to another namespace getting Multi-Attach volume error in the sshd pod description.

Below is the command used:
pv-migrate migrate \
  --source-kubeconfig /path/to/source/kubeconfig \
  --source-context some-context \
  --source-namespace source-ns \
  --dest-kubeconfig /path/to/dest/kubeconfig \
  --dest-context some-other-context \
  --dest-namespace dest-ns \
  --ignore-mounted \
  --dest-delete-extraneous-files \
  old-pvc new-pvc

With the above command, though it is showing the below but the copy is not successful with Multi Attach volume error

💡  PVC <pvc> is mounted to node <node>, ignoring...

**Expected behavior**
With the option --ignore-mounted source pvc should be able to copy to destination pvc without failure.

**Comment by sshingarapu** [comment]
I have rechecked this with the new set of pvc's. I have three pvc's using by 3 different pods. 

It worked for two of the pvc's (that means sshd pod landed on the same node where my pod is running) but it did not work for other pvc as the sshd pod is landed on some other node.

I confirmed this by running pv-migrate multiple times with option --ignore-mounted.

I am using dynamic provisioners from GKE.

**Comment by utkuozdemir** [comment]
I see. In the past, the code had the logic to schedule SSHD pod on the same node when ignore-mounted was requested but now I see that it's not in the code - probably I introduced a regression somewhere.

I'll add the logic back and make a new release when I find some time. In the meantime you can pass `--helm-set sshd.nodeName=<NODE>` or `--helm-set sshd.nodeSelector=<...>` (and the same for the rsync - see the [available helm values](https://github.com/utkuozdemir/pv-migrate/tree/master/helm/pv-migrate)) to work around the issue.

**Comment by sshingarapu** [comment]
Thanks for all your help. Please let me know once you release the new version meanwhile i will use --hel-set sshd.nodeName=<NODE>

**Comment by utkuozdemir** [comment]
@sshingarapu fyi, just released `v1.0.0` with the feature included.

**Comment by sshingarapu** [comment]
Thank you for all your support.
