### ISSUE TITLE
Error: exec plugin: invalid apiVersion "client.authentication.k8s.io"/v1alpha1"

### ISSUE THREAD

**Issue by safag05** [utkuozdemir/pv-migrate#185]
**Describe the bug**
pv-migrate does not work with Kubernetes version 1.24+

**To Reproduce**
1. I was trying to run `pv-migrate` from EKS cluster v1.16 to GKE cluster v1.24 
2. `Error: exec plugin: invalid apiVersion "client.authentication.k8s.io"/v1alpha1"`

**Expected behavior**
Migrate pvc from EKS v1.16 to GKE v1.24

**Console output**
`Error: exec plugin: invalid apiVersion "client.authentication.k8s.io"/v1alpha1"`

**Version**
 - Source and destination Kubernetes versions `v1.16`, `v1.24`
 - `pv-migrate` version and architecture `v1.0.0 - darwin_x86_64`
 - Installation method binary download

**Additional context**
Kubernetes [ChangeLog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md) states the following
`The client.authentication.k8s.io/v1alpha1 ExecCredential has been removed. If you are using a client-go credential plugin that relies on the v1alpha1 API please contact the distributor of your plugin for instructions on how to migrate to the v1 API.`

**Comment by utkuozdemir** [comment]
I suspect this is not an issue of `pv-migrate`. Please check this out: https://github.com/aws/aws-cli/issues/6920#issuecomment-1171113816

Please give a try to the various solutions recommended in the ticket above and see if they help.

**Comment by safag05** [comment]
Awesome, thank you @utkuozdemir! That has solved that error but now facing some authentication error. `decoding stdout: no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme` will look into it

**Comment by safag05** [comment]
@utkuozdemir didn't get much time to look in depth. I was not able to figure it out. I do not think I will continue to investigate since we have decided not to move the pv data. Thanks for the amazing tool with all the useful use-cases!
