### ISSUE TITLE
all pvc's from one namespace to another cluster?

### ISSUE THREAD

**Issue by tstark7952** [utkuozdemir/pv-migrate#202]
is it possible to pv migrate all pvc's from one cluster to another? like one script that is *.pvc in this namespace to another? also when you run pv migrate a seond time does it already rsync only incremental changes on the source, if not can we do this?

**Comment by utkuozdemir** [comment]
> is it possible to pv migrate all pvc's from one cluster to another? like one script that is *.pvc in this namespace to another?

No, but you can use this tool in a bash script to achieve what you need.

> also when you run pv migrate a seond time does it already rsync only incremental changes on the source
yes, it uses regular rsync command which works incrementally.

**Comment by tstark7952** [comment]
[errors.txt](https://github.com/utkuozdemir/pv-migrate/files/9982763/errors.txt)
i am trying to run this from one gke cluster to another and sometimes it works and sometimes it fails with ssh errors. it looks like the tool is trying to ssh into the k8s master which google doesnt allow, could you tell me how to get consistent results if possible?

**Comment by utkuozdemir** [comment]
It does not try to SSH into any node. It tries to SSH into the pod it creates over a LoadBalancer type service (with IP `34.23.5.115` in your case).

Can you run it via `--log-level debug --log-format json` and share the full logs here?

**Comment by tstark7952** [comment]
can we force the tool to use internal gke load balancers, this is opening up port 22 to the entire world

**Comment by utkuozdemir** [comment]
Yes, AFAIK it is done using annotations on the Service. Using `--helm-*` flags you can customize the service annotations - see https://github.com/utkuozdemir/pv-migrate/blob/master/helm/pv-migrate/values.yaml#L40

**Comment by tstark7952** [comment]
trying to run this below for more than a single pvc, how can i do that?  

pv-migrate migrate \
  --source-kubeconfig /path/to/source/kubeconfig \
  --source-context some-context \
  --source-namespace source-ns \
  --dest-kubeconfig /path/to/dest/kubeconfig \
  --dest-context some-other-context \
  --dest-namespace dest-ns \
  --dest-delete-extraneous-files \
  old-pvc new-pvc

**Comment by utkuozdemir** [comment]
> pv-migrate migrate
> --source-kubeconfig /path/to/source/kubeconfig
> --source-context some-context
> --source-namespace source-ns
> --dest-kubeconfig /path/to/dest/kubeconfig
> --dest-context some-other-context
> --dest-namespace dest-ns
> --dest-delete-extraneous-files
> old-pvc new-pvc

As I mentioned, you can wrap the tool in a bash script for loop. Here's an example:
https://gist.github.com/utkuozdemir/8f775656b75843a5bf0f17f6db12e12a

**Comment by utkuozdemir** [comment]
Closing, as it can be easily addressed with my suggestion above.
