### ISSUE TITLE
Flag to alter service load balancer timeout

### ISSUE THREAD

**Issue by nderjung** [utkuozdemir/pv-migrate#203]
**Is your feature request related to a problem? Please describe.**
The service load balancer migration method is usually the most reliable method for a given cluster.  However, it occasionally fails without proper reason.  A deeper inspection shows that the load balancer can simply be waiting a longer length of time to receive an external IP address greater than the hard coded limit.  This results in a premature failure on the `lbsvc` migration method since the service has simply yet to receive a public IP.

This issue tracks the addition of a new command-line argument `--timeout` (or similar) such that the values associated with wait times in `pv-migrate` are variabilised beyond the default value (set to 120s).

**Describe the solution you'd like**
Modify the built in assumption (see below) such that its value is configurable via a new command-line argument flag `--timeout`.

https://github.com/utkuozdemir/pv-migrate/blob/1c4d4cdbcbaa3c89d715e311bb0efd3007c6c515/internal/k8s/service.go#L20

Perhaps this information should also be propagated to the user who may not realise that the migration fails due to wait times? Additional context provided in the help menu may suggest guidance for when this particular migration method has failed.

**Describe alternatives you've considered**
There is no alternative to this solution, perhaps ask your vendor to provision public IP addresses faster. ;)

**Additional context**
N/A.

**Comment by utkuozdemir** [comment]
Makes total sense, it shouldn't have been hardcoded in the first place. I'll try to get this done some time. If you feel like doing it, please proceed :)

**Comment by nderjung** [comment]
Hi, i have made the modifications but have yet to test them.  I will open a PR fixing this issue, if you could test it your end that would be great.

**Comment by tstark7952** [comment]
yes this is what i was running into on google gke, sometimes the copy will work and other times it will fail.  any way i can manually set the timeout higher?

**Comment by utkuozdemir** [comment]
> yes this is what i was running into on google gke, sometimes the copy will work and other times it will fail. any way i can manually set the timeout higher?

It will come as a PR from @nderjung . Until then only way is to change it in the code and build it yourself.

**Comment by danotrampus** [comment]
Any update on this?

**Comment by utkuozdemir** [comment]
Implemented in https://github.com/utkuozdemir/pv-migrate/pull/215

and included in `v1.1.0`.

You can now set it using `--lbsvc-timeout` flag, for example `pv-migrate m --lbsvc-timeout 10m ...`.
