### ISSUE TITLE
AlmaLinux9/RKE2 Selinux blocks pv-migrate

### ISSUE THREAD

**Issue by dragon2611** [utkuozdemir/pv-migrate#220]
It seems SELINUX is blocking rsync from accessing the volume, pvmigrate works if selinux is set to permissive.

Almalinux 9 / RKE2 v1.25.9+rke2r1

`rsync: [sender] change_dir "/source/" failed: Permission denied (13)
              0 100%    0.00kB/s    0:00:00 (xfr#0, to-chk=0/0)
`

**Comment by BonzTM** [comment]
> It seems SELINUX is blocking rsync from accessing the volume, pvmigrate works if selinux is set to permissive.
> 
> Almalinux 9 / RKE2 v1.25.9+rke2r1
> 
> `rsync: [sender] change_dir "/source/" failed: Permission denied (13) 0 100% 0.00kB/s 0:00:00 (xfr#0, to-chk=0/0) `

Temporarily set your SELinux policy to permissive, migrate, then set back.

**Comment by utkuozdemir** [comment]
I think it is out-of-scope for this tool to make meet SELinux requirements. I would suggest the same as @BonzTM. Closing.

**Comment by log1cb0mb** [comment]
just run sshd as privileged using `sshd.securityContext.privileged=true` or `sshd.securityContext.seLinuxOptions.type=spc_t`
