### ISSUE TITLE
Set preferredDuringSchedulingIgnoredDuringExecution  weight to something higher depending on the usecase

### ISSUE THREAD

**Issue by son-la** [utkuozdemir/pv-migrate#224]
**Is your feature request related to a problem? Please describe.**
When PVC is RWO and being attached to a node, preferredDuringSchedulingIgnoredDuringExecution with weight 1 is sometimes nt enough for `pv-migrate` to work

sshd pod can be scheduled in the different node and cannot attach the PVC

**Describe the solution you'd like**
It is possible to set the weight of preferredDuringSchedulingIgnoredDuringExecution. Depending on the volume mode e.g. RWO and status e.g.: attaching to pod, it must be required even, not preferred. 

**Describe alternatives you've considered**
Right now in order for this to work, I need to cordon all other nodes except for one that the PVC is attaching to

Or quickly when sshd is deployed, I modify the weight to 100 

**Additional context**

**Comment by utkuozdemir** [comment]
Good point, thanks.

I'm wondering why weight of `1` is not enough - what causes some other node to have a higher weight at the end. I had the impression that only the weight in the pod spec would be taken into consideration - no external factors would be considered.

I chose it to be `preferredDuringSchedulingIgnoredDuringExecution` to keep the tool best-effort, but yes, probably for RWO `required...` would make sense as well.

Would updating the `weight` to be `100` help instead?
