### ISSUE TITLE
Exclude/include

### ISSUE THREAD

**Issue by awbait** [utkuozdemir/pv-migrate#228]
Hi, can we somehow pass additional flags to rsync? For example, to exclude/include files/folders according to a specific pattern?

**Comment by utkuozdemir** [comment]
Currently not possible, but I might add some customization options when I find some time.

**Comment by babykart** [comment]
We need this feature too.
Thanks in advance.

**Comment by utkuozdemir** [comment]
It is possible to pass additional arguments to rsync now: 0c934ca8eedead440e41928eb0dd1ff9c5fe490c

Please see the examples: https://github.com/utkuozdemir/pv-migrate/blob/master/USAGE.md#example-6-passing-additional-rsync-arguments

This should cover the requirement. Let me know if it does not help.
