### ISSUE TITLE
`chown` fails

### ISSUE THREAD

**Issue by angelabad** [utkuozdemir/pv-migrate#23]
Hi, I will try to use pv-migrate (great software...) with aws-efs-csi-driver, this csi fails when you try to do chown, you can see at:

- https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300

I got this error:

```
WARNING[2021-04-28T12:15:55+02:00] Migration failed, will try remaining strategies  error="job failed with pod logs: rsync: [generator] chown \"/dest/png\" failed: Operation not permitted (1)\n\r         32.77K   6%    0.00kB/s    0:00:00  \r        520.19K 100%  464.84MB/s    0:00:00 (xfr#1, to-chk=2/4)\nplugins/\npng/\nrsync: [receiver] chown \"/dest/.grafana.db.CpcBci\" failed: Operation not permitted (1)\n\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=v3.13.0_rc2-264-g725ac7fb]\nsent 16.89K bytes  received 50 bytes  11.29K bytes/sec\ntotal size is 520.19K  speedup is 30.70\nRsync job failed after 5 retries\n" priority=1000 strategy=mount-both
```

It could be possible to avoid chown/chmod use?

Thanks

**Comment by utkuozdemir** [comment]
Thanks for the feedback and reporting this. I will look into adding the feature.

**Comment by utkuozdemir** [comment]
No problem. In half an hour or so, I will release version `v0.5.1`, please give it a try and let me know if you have any problems.
