### ISSUE TITLE
libsvc job should support configurable retries

### ISSUE THREAD

**Issue by MarkSRobinson** [utkuozdemir/pv-migrate#240]
**Is your feature request related to a problem? Please describe.**
Kubernetes and DNS can take more than 50 seconds for everything to come completely healthy. I would like to be able to extend how long the retry job runs before giving up.

**Describe the solution you'd like**
A setting in the helm chart that controls how many retries the Job tries before quitting would be perfect. Set the default to 10, but I might want to set it to 30 because AWS can be slow.

**Describe alternatives you've considered**
As it stands, I have to edit the job definition in the source code and compile which isn't a great user experience.

**Comment by utkuozdemir** [comment]
I agree, will make the number of retries and duration between retries configurable, when I find the chance. PRs welcome.

**Comment by utkuozdemir** [comment]
Closed by https://github.com/utkuozdemir/pv-migrate/pull/239
