### ISSUE TITLE
pv-migrate should allow for resuming transfers

### ISSUE THREAD

**Issue by MarkSRobinson** [utkuozdemir/pv-migrate#241]
My problem is that if I'm migrating a large PVC, it can take a long time. If my pv-migrate job is interrupted then I need to start over.

I've found that if I add `"--partial", "--inplace", "--append"` to the rsync command I can resume a transfer.  I'm using libsvc to migrate across clusters.

This dropped the time to 'redo' a transfer from a day to just a few minutes as I only needed to update the changed blocks.

**Comment by utkuozdemir** [comment]
I like the idea. pv-migrate cannot possibly support all rsync flags, but we can allow additional flags to be passed to it by user. Right now it is possible to override the `rsync.command` value of the helm chart, but as the tool itself generates a (potentially complex) rsync command, overriding it as a user is pretty problematic.

I can think of a way like introducing a new helm chart value, `rsync.extraFlags`, to allow adding additional flags. So the usage would look like `pv-migrate --helm-set rsync.extraFlags="--partial ..." source dest`.

**Comment by utkuozdemir** [comment]
Closed by 0c934ca8eedead440e41928eb0dd1ff9c5fe490c

Please see the examples: https://github.com/utkuozdemir/pv-migrate/blob/master/USAGE.md#example-6-passing-additional-rsync-arguments
