### ISSUE TITLE
Add Helm rsync.fixPrivateKeyPerms option

### ISSUE THREAD

**Issue by alex-vmw** [utkuozdemir/pv-migrate#246]
**Is your feature request related to a problem? Please describe.**
In our Kubernetes Cluster `securityContext.fsGroup` is required for every Pod. When `securityContext.fsGroup` is set, the `defaultMode=256` for the private key secret is NOT respected (https://github.com/kubernetes/kubernetes/issues/57923) and private key ends up having `0440` permissions instead of `0400`, which in turn leads to rsync over ssh failure:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0440 for '/root/.ssh/id_ed25519' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_ed25519": bad permissions
```

**Describe the solution you'd like**
Can we add Helm rsync.fixPrivateKeyPerms option (`bool`), which if set to `true` would run `chmod 400 {{ .Values.rsync.privateKeyMountPath }}` before running rsync and fix the permissions for the ssh private key? Perhaps something like this below in the https://github.com/utkuozdemir/pv-migrate/blob/master/helm/pv-migrate/templates/rsync/job.yaml file:
```
          command:
            - sh
            - -c
            - |
              set -x
              n=0
              rc=1
              retries={{ .Values.rsync.maxRetries }}
              period={{ .Values.rsync.retryPeriodSeconds }}
              {{- if .Values.rsync.fixPrivateKeyPerms -}}
              chmod 400 {{ .Values.rsync.privateKeyMountPath }}
              {{- end }}
              until [ "$n" -ge "$retries" ]
              do
              ...
```

**Describe alternatives you've considered**
Not able to find any alternatives unfortunatelly.

**Additional context**
None

**Comment by utkuozdemir** [comment]
The solution makes total sense to me. Please feel free to submit a PR with the fix you suggested.
(Do not forget to do `task update-chart`) after making changes in the chart.

**Comment by alex-vmw** [comment]
@utkuozdemir It appears that I underestimated this issue. SSH key is being mounted from a secret and apparently in Kubernetes secret mounts are always ReadOnly (https://github.com/kubernetes/kubernetes/issues/62099). Since mounted SSH Key is always ReadOnly, trying to chmod it gives `chmod: /root/.ssh/id_ed25519: Read-only file system` error. That said, I think the only solution would be to copy the SSH key somewhere (`/tmp` maybe?) and somehow pass the `-i /tmp/<PrivateKey>` option to ssh command. That said, I need your guidance on what would be the best way to add that `-i` option to ssh? I see sshArgs defined in https://github.com/utkuozdemir/pv-migrate/blob/b563c1b5115d677e141a9d4eb8ed75e5c53cfee0/rsync/cmd.go#L34, so do I need to create another command line option like `--ssh-key-path` and use the passed string to set the `-i` option to ssh and add it to `sshArgsStr` (https://github.com/utkuozdemir/pv-migrate/blob/master/rsync/cmd.go#L42)?

**Comment by utkuozdemir** [comment]
I see. No problem. What if we do something like:
- Always mount the private key to `/tmp` or `/opt` or something
- On rsync job, we
  - `mkdir -p ~/.ssh`
  - Copy it from `/tmp` into `~/.ssh`
  - `chmod` if the flag is specified

Also, I'll ask you to please build and test manually & change/add integration tests for the further changes so we avoid further broken functionality.

**Comment by alex-vmw** [comment]
@utkuozdemir I like your idea, but I think it would be advantageous to not have a flag for chmod. I think chmod of the private key after copying should be done always by default. It wouldn't hurt anything and wouldn't require people to provide any extra flag for things to work correctly. WDYT?

**Comment by utkuozdemir** [comment]
Yep, actually that sounds reasonable - always mount it to a temp path, always copy and chmod 400. Should work just fine and less complexity. We can give it a shot.

**Comment by alex-vmw** [comment]
@utkuozdemir In my usecase, I don't need any changes for `sshd` deployment, but I see that `sshd.privateKeyMountPath` exists. I should skip modifying anything for `sshd`, right?

**Comment by utkuozdemir** [comment]
I had to look into the code to remember what it was used for, it seems I use it in the local strategy. Let's also change it to be the new way.

**Comment by alex-vmw** [comment]
@utkuozdemir I also assume I would be removing the `rsync.fixPrivateKeyPerms` with this change, right?

**Comment by utkuozdemir** [comment]
Yep, we'll just make a minor release because of the breaking change and it should be fine.

**Comment by alex-vmw** [comment]
@utkuozdemir I was trying to verify that setting `sshd.privateKeyMount=true` is working, but even without any of my latest changes running `pv-migrate` with `--helm-set sshd.privateKeyMount=true` seems to fail (for any strategy).
P.S. Running `--strategies "local"` without also specifying `--helm-set sshd.privateKeyMount=true` seems to work fine.

**Comment by utkuozdemir** [comment]
Hm, interesting, we set it to true here: https://github.com/utkuozdemir/pv-migrate/blob/master/strategy/local.go#L197

And the integration test that tests local strategy passes without issues. Doing `--helm-set sshd.privateKeyMount=true` explicitly shouldn't change anything actually.
