### ISSUE TITLE
Doc Request: another use case that would have led me here faster

### ISSUE THREAD

**Issue by HWiese1980** [utkuozdemir/pv-migrate#271]
I suggest adding another use case to the README: changing the StorageClass of a volume. 

I'm migrating all my PVC/PVs from one storage class to another. Initially I thought I would have to do this manually. Thankfully I found pv-migrate that can simply do this automatically in the very same way that it migrates between basically anything regarding PVC/PV. 

However, it took me quite some time of research to find this neat little tool, pv-migrate, because I was searching explicitly for tools to change the StorageClass of volumes. I suppose I would have come here way quicker if this use case had been mentioned in the README. And I suppose, it's not that uncommon too. Example (my case actually): I want to migrate from a StorageClass that only supports ReadWriteOnce to one that allows ReadWriteMany. Or move from a StorageClass that stores the volume data on a node (local-path) to one that stores it somewhere on the network (NFS). I think it's common enough to be mentioned.

**Comment by utkuozdemir** [comment]
That's a good point, thanks. We can add it to the use cases. Feel free to raise a PR, otherwise I'll do it when I find some time.

**Comment by utkuozdemir** [comment]
Closed by https://github.com/utkuozdemir/pv-migrate/pull/272

Thanks!
