### ISSUE TITLE
bash completion only working for pv-migrate, not for the kubectl plugin

### ISSUE THREAD

**Issue by johanneskastl** [utkuozdemir/pv-migrate#289]
**Describe the bug**
The bash completion is working, but only if the tool is being called as `pv-migrate`, not when being used as a kubectl plugin.

**To Reproduce**
1. Install `pv-migrate` as well as `kubectl-pv_migrate`
1. Type `pv-migrate` followed by a space and `TAB` `TAB` => bash completion
1. Type `kubectl pv-migrate` followed by a space and `TAB` `TAB` => list of files and directories in current directory

**Expected behavior**
It would be nice if the completion worked for both types of usage.

**Version**
 - `pv-migrate` version and architecture: 1.7.1 x86_64
 - Installation method manually built on openSUSE and binary download

**Comment by utkuozdemir** [comment]
kubectl plugins do not support completion, see https://github.com/kubernetes/kubernetes/issues/74178
