### ISSUE TITLE
Does this project need a new maintainer?

### ISSUE THREAD

**Issue by Pandry** [utkuozdemir/pv-migrate#3]
As the title says, I was wondering if this project needed a new maintainer; 
Mostly because @cgroschupp did open a PR a while ago, and it's still open.
I also forked the project to try to avoid using a network copy if possible (my code is pretty ugly, to be honest, but still).
There are multiple situations where this could result in being a super useful tool, so that's the reason behind the question.
I would be interested in contributing too.
Regards

**Comment by utkuozdemir** [comment]
It does indeed.

I want to get back to it at some point but cannot find time and/or motivation to do it since a long time.
If you would be up for it I can add you as a contributor/maintainer, or update the README to point to your fork/project.

Just let me know :)

**Comment by Pandry** [comment]
I see

It looks like most of the stuff is already there, and since you are the owner and acknowledge that, I don't think that there is a particular reason to have my own fork.

I also saw that @cgroschupp made PR that looks nice so far, so I would also include him in the conversation.

Imho, if it's not an issue for you, some maintainer could be added so that it could be possible to manage the project without your direct intervention.

Otherwise, it's ok for me to continue developing on my own fork.

Let me know what you think
(Also sorry for being so late, busy period)

**Comment by utkuozdemir** [comment]
@Pandry I would gladly add you or @cgroschupp as a maintainer. Would any of you be interested?

**Comment by cgroschupp** [comment]
@utkuozdemir Yes, I am interested.

**Comment by utkuozdemir** [comment]
Update: since there is a bit interest, I got back to the project today and did some set of improvements. Still, I cannot say how much or often I can commit to this project, so I am still open to adding an additional maintainer.

**Comment by Pandry** [comment]
Just saw the @cgroschupp's PR were closed and merged! Congrats!
I could look into eventually rebasing my repo and pushing it, but I need to review the code before
In the meantime, glad to know the project is not dead! :D

**Comment by utkuozdemir** [comment]
Added @cgroschupp as collaborator.
I will also try to maintain the project in the future.
Therefore closing this issue.
