### ISSUE TITLE
Migration got halfway, now fails with rsync error: error in rsync protocol data stream (code 12) at io.c(228)

### ISSUE THREAD

**Issue by mark-webster-catalyst** [utkuozdemir/pv-migrate#309]
Running a migration between EKS clusters in the same account via the lbscv strategy. It transferred about 140/300GB, but now keeps failing with the error:
```
Connection to xxx.eu-west-2.elb.amazonaws.com closed by remote host.
rsync: connection unexpectedly closed (17531029 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [receiver=3.2.3]
```
Initial transfer happened at a good speed, but slowed down and eventually died with the above error. Now I just keep getting the error.

Both PVCs are EFS backed using the AWS EFS CSI driver. Both ReadWriteMany.

Command used is:

```
kubectl pv-migrate \
  --source-kubeconfig path/to/kubeconfig.yaml \
  --source-context context1 \
  --source-namespace nextcloud \
  --source nextcloud-sitedata \
  --dest-kubeconfig path/to/kubeconfig.yaml \
  --dest-context context2 \
  --dest-namespace nextcloud \
  --dest-delete-extraneous-files \
  --dest nextcloud-sitedata \
  --ignore-mounted \
  --strategies lbsvc \
  --helm-set rsync.maxRetries=20,rsync.retryPeriodSeconds=60 \
  --lbsvc-timeout 10m \
  --no-chown \
  --log-level DEBUG \
  --log-format json
```

**Comment by utkuozdemir** [comment]
For example, check this out, it seems similar to your issue https://askubuntu.com/a/1395264

**Comment by mark-webster-catalyst** [comment]
It's EFS, the volume reports as being 8 exabytes, so seems unlikely :laughing:

**Comment by mark-webster-catalyst** [comment]
I changed nothing an now it's working again. Guessing it was an AWS issue. Probably hit some kind of rate limit somewhere (nothing was jumping out in CloudWatch though). Closing.
