### ISSUE TITLE
[Question] How would you go about migrating data fully before letting the main process start?

### ISSUE THREAD

**Issue by omerxx** [utkuozdemir/pv-migrate#314]
Hi,
I'd like to migrate PVCs from one database to another. However, I don't want the DB process to start because it'll start joining my cluster or serving users. Beyond, I'd like to use it with other applications and only let them start when the data is fully migrated.
Is there a feature of the tool that allows this? Should I use something like an init container?
What do you guys normally do?

**Comment by utkuozdemir** [comment]
This tool is completely agnostic to such cases, it simply copies the data over. If the source or destination PVC is already mounted to a pod, it fails explicitly, unless `--ignore-mounted` flag is set.

So what you would want to do is, scale the database workload (deployment/statefulset) to zero, do the migration and then scale it back up.

Also, to clarify, this tool's main use case is for one-off migrations, not sync'ing data continuously or so. So an init container etc. do not make much sense imo. But ofc, it always depends on what you need exactly.

**Comment by utkuozdemir** [comment]
Closing, as synchronizing/coordinating further actions than the actual data migration is out-of-scope of this project.
