### ISSUE TITLE
a problem with lbsvc migration strategy | ("Migration failed with this strategy, will try with the remaining strategies" error="timed out waiting for the condition" strategy=lbsvc)

### ISSUE THREAD

**Issue by doctor500** [utkuozdemir/pv-migrate#41]
**Describe the bug**
Hi there, thanks for creating these good tools. but, it looks like there's something wrong when I'm using it. I plan to migrate our persistent volume to a new cluster. It looks like there's a problem when the new cluster SSH remote to pods created in the old cluster. I'll break down the cluster specs below. Is there something problem with my parameter or there's something else?
Looking forward to your responses, thanks! 😊

**To Reproduce**
```
./pv-migrate.exe migrate \
  --source-context old-public-cluster \
  --source-namespace default \
  --dest-context new-private-cluster \
  --dest-namespace artifact \
  archiva archiva-pvc

```
**Expected behavior**
Success

**Console output**
```shell
time="2021-05-26T01:18:58+07:00" level=info msg="Will attempt 3 strategies" dest=artifact/archiva-pvc source=default/archiva strategies="mnt2,svc,lbsvc"
time="2021-05-26T01:18:58+07:00" level=info msg="Attempting strategy" strategy=lbsvc
time="2021-05-26T01:18:58+07:00" level=info msg="Generating RSA SSH key pair"
time="2021-05-26T01:18:58+07:00" level=info msg="Creating secret for the public key"
time="2021-05-26T01:18:58+07:00" level=info msg="Creating sshd pod" podName=pv-migrate-sshd-hry4t
time="2021-05-26T01:18:58+07:00" level=info msg="Waiting for the sshd pod to start running" podName=pv-migrate-sshd-hry4t
time="2021-05-26T01:19:16+07:00" level=info msg="Sshd pod running" podName=pv-migrate-sshd-hry4t
time="2021-05-26T01:19:22+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=5 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:27+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=10 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:31+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=15 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:37+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=20 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:42+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=25 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:47+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=30 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:52+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=35 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:19:57+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=40 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:20:02+07:00" level=info msg="Waiting for LoadBalancer IP" elapsedSecs=45 intervalSecs=5 service=pv-migrate-sshd-hry4t timeoutSecs=120
time="2021-05-26T01:20:07+07:00" level=info msg="Creating secret for the private key"
time="2021-05-26T01:20:07+07:00" level=info msg="Connecting to the rsync server" targetHost=xx.xxx.xxx.xxx
time="2021-05-26T01:22:10+07:00" level=info msg="Cleaning up"
time="2021-05-26T01:22:11+07:00" level=warning msg="Migration failed with this strategy, will try with the remaining strategies" error="timed out waiting for the condition" strategy=lbsvc
time="2021-05-26T01:22:11+07:00" level=info msg="Attempting strategy" strategy=mnt2
time="2021-05-26T01:22:11+07:00" level=info msg="Strategy cannot handle this migration, will try the next one" strategy=mnt2
time="2021-05-26T01:22:11+07:00" level=info msg="Attempting strategy" strategy=svc
time="2021-05-26T01:22:11+07:00" level=info msg="Strategy cannot handle this migration, will try the next one" strategy=svc
time="2021-05-26T01:22:11+07:00" level=fatal msg="all strategies have failed"
```

**Version**
 - Source Kubernetes versions `1.18.17-gke.100`
 - Destination Kubernetes versions`1.18.17-gke.100` (when this command executed)(current: `1.18.17-gke.700`)
 - Source and destination container runtimes `docker://19.3.14`
 - `pv-migrate` version and architecture `pv-migrate_0.5.5_windows_x86_64`
 - Installation method `binary download`
 - Source PVC Specs:
 ```
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
 ```
 - Destination PVC Specs:
```
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

**Additional context**
- The source cluster configured in the public networking cluster
- The destination cluster configured in the private networking cluster
- Using the GKE Platform

**Comment by utkuozdemir** [comment]
Hi! Thanks for the bug report. I'll have a look into it and try to reproduce.
Your report already made me notice a bug - strategies are not run in the correct order - `lbsvc` should be run as the last strategy, not the first one. I somehow overlooked this and it is a very simple fix, but thanks for bringing it to my attention :)

However, in your case `lbsvc` is the correct one anyways, since you are trying to do a cross-cluster migration.

For now, 2 questions:
1. Is your destination cluster have internet access at all? Because normally GKE clusters with private network do not have internet access, unless you configure a cloud NAT gateway. In your case, internet access is **required**, because basically rsync will be done over the internet.
2. Are PodSecurityPolicies enabled in any of these 2 clusters by chance?

**Comment by doctor500** [comment]
Hi @utkuozdemir thanks for noticing it, It works after I attaching Cloud NAT for the private cluster 👏. I'll close it if there's no more problem in the migration process or reply it again if there is another problem that happened

**Comment by utkuozdemir** [comment]
Glad to hear it :) Your plan sounds good

**Comment by doctor500** [comment]
Look's like the problem is just from my configuration on Cloud NAT before, thanks for fast replying to my cases. Sorry for the inconvenience and thanks @utkuozdemir :D

**Comment by utkuozdemir** [comment]
No problem at all @doctor500 . Happy to hear that the tool actually solves problems. Also, I discovered another issue thanks to you, which I have just solved 😄: https://github.com/utkuozdemir/pv-migrate/pull/42
