### ISSUE TITLE
x86_64 cli doesnt work 

### ISSUE THREAD

**Issue by amos-baron** [utkuozdemir/pv-migrate#44]
**Describe the bug**
cli for x86_64 linux does not work 
**To Reproduce**
1. run the command pv-migrate for x86_64 linux on a linux machine with AMD64 processor 

**Expected behavior**
for it to work 
**Console output**
-bash /usr/local/bin/pv-migrate: cannot excecute binary file 
**Version**
0.5.8

**Comment by utkuozdemir** [comment]
I have tested it on a server of my own that runs Ubuntu 20.04 and is amd64 processor, and it works fine.
Can you tell me which installation method did you follow?

Also, please check that you have downloaded the correct archive:
```
e91745ff7b8e8b30bd6eeced144a31775cc690c5c805244c480568cf8583bb57  pv-migrate_0.5.8_linux_x86_64.tar.gz
```

and make sure that you have execute permissions:
`chmod a+x /usr/local/bin/pv-migrate`
