### ISSUE TITLE
changing the default image used 

### ISSUE THREAD

**Issue by amos-baron** [utkuozdemir/pv-migrate#45]
**Is your feature request related to a problem? Please describe.**
when trying to use pv-migrate in an air-gapped environment pv-migrate cannot work because it has no contact with docker.io and thus cannot pull the used image

**Describe the solution you'd like**
a flag like `pv-migrate --image`

**Describe alternatives you've considered**
currently I'm using imageContentSourcePolicy to change docker.io to my internal registry but this is not a good fix

**Comment by utkuozdemir** [comment]
Please see the output of `pv-migrate migrate --help` - the feature is already implemented.
```
--rsync-image value, -r value        Image to use for running rsync (default: "docker.io/utkuozdemir/pv-migrate-rsync:alpine-3-20210522")
--sshd-image value, -S value         Image to use for running sshd server (default: "docker.io/utkuozdemir/pv-migrate-sshd:alpine-3-20210522")
 ```

You'll need 2 images: one with rsync installed, another working as sshd server on port 22.
Of course, you can use the same image for both.

**Comment by amos-baron** [comment]
awsome thanks :)
