### ISSUE TITLE
[feature] add kubectl-krew plugin

### ISSUE THREAD

**Issue by Slach** [utkuozdemir/pv-migrate#51]
**Is your feature request related to a problem? Please describe.**
install method via `kubectl krew install pv-migrate` could increase this tool distribution 

**Describe the solution you'd like**
Look to https://krew.sigs.k8s.io/docs/developer-guide/develop/plugin-development/

**Comment by utkuozdemir** [comment]
done https://github.com/kubernetes-sigs/krew-index/pull/1839
