### ISSUE TITLE
pv-migrate stays timeless in "Connecting to the rsync server" status

### ISSUE THREAD

**Issue by guasky13** [utkuozdemir/pv-migrate#78]
**Describe the bug**
When I execute any pv-migrate command, the process stays for ever in the step "Connecting to the rsync server" and never pass to the next step.

**To Reproduce**
1. Run command pv-migrate -i old_pvc new_pvc
2. See error

**Expected behavior**
Pass all the steps and migrate pvcs.

**Console output**
`pol.guasch@vdi-linux-sis-2:~$ pv-migrate migrate -i --source-namespace spservicelevels --dest-namespace spservicelevels mssql-linux-master mssql-linux-master-new
🚀  Starting migration
💡  PVC mssql-linux-master is mounted to node kubernetes-worker-05, ignoring...
💭  Will attempt 3 strategies: mnt2,svc,lbsvc
🚁  Attempting strategy: mnt2
🦊  Strategy 'mnt2' cannot handle this migration, will try the next one
🚁  Attempting strategy: svc
🔑  Generating SSH key pair
🔑  Creating secret for the public key
🚀  Creating sshd pod
⏳  Waiting for the sshd pod to start running
🚀  Sshd pod started
🔑  Creating secret for the private key
🔗  Connecting to the rsync server
:warn: Cannot tail logs to display progress

`

**Version**
 Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

 - `pv-migrate` version and architecture [e.g. `v0.5.10 - linux_x86_64`]
 - Installation method [ binary download]

**Additional context**
I can't access to the pod and see what happen.

`pol.guasch@vdi-linux-sis-2:~$ k exec -it pv-migrate-rsync-phqvx-rv6d6 -c app sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: unable to upgrade connection: container not found ("app")
`

**Comment by utkuozdemir** [comment]
Need some more debugging info. Can you please check the following:
- `kubectl describe pod pv-migrate-rsync-...`
- `kubectl describe pod pv-migrate-sshd-...`
- `kubectl logs pv-migrate-rsync-...`
- `kubectl logs pv-migrate-sshd-...`

And share their output here?

Also, do you use `PodSecurityPolicy` or `NetworkPolicy` resources in your cluster?

**Comment by guasky13** [comment]
Hello,

My problem was caused by Istio.

Disabling "Istio Auto Injection" the migration is succeeded.

We can close the issue.
